export const demoOrders = {
  "AYU-2025-001": {
    id: "AYU-2025-001",
    product: "Under Eye Cream + Herbal Glow Serum",
    placed: "March 10, 2025",
    estimatedDelivery: "March 20, 2025",
    amount: "₹1,280",
    customer: "Riya Nair",
    phone: "+91 98765 43210",
    address: "42, Anna Salai, Chennai, Tamil Nadu - 600002",
    courier: "BlueDart",
    awb: "BD9284710023",
    currentStep: 3,
    steps: [
      { label: "Order Confirmed", desc: "Your order has been received & confirmed.", date: "Mar 10, 10:32 AM", icon: "confirm" },
      { label: "Processing", desc: "Items packed & quality checked at our facility.", date: "Mar 11, 02:14 PM", icon: "process" },
      { label: "Shipped", desc: "Handed over to BlueDart. AWB: BD9284710023", date: "Mar 12, 09:00 AM", icon: "truck" },
      { label: "Out for Delivery", desc: "Your package is with the delivery executive.", date: "Mar 19, 08:45 AM", icon: "warehouse" },
      { label: "Delivered", desc: "Package delivered successfully.", date: null, icon: "box" },
    ],
  },
  "AYU-2025-002": {
    id: "AYU-2025-002",
    product: "Vitamin C Brightener + Hair Growth Serum",
    placed: "March 14, 2025",
    estimatedDelivery: "March 23, 2025",
    amount: "₹990",
    customer: "Karthik S",
    phone: "+91 91234 56789",
    address: "7, Nehru Street, Coimbatore, Tamil Nadu - 641001",
    courier: "Delhivery",
    awb: "DEL7731094882",
    currentStep: 2,
    steps: [
      { label: "Order Confirmed", desc: "Your order has been received & confirmed.", date: "Mar 14, 11:00 AM", icon: "confirm" },
      { label: "Processing", desc: "Items packed & quality checked at our facility.", date: "Mar 15, 01:30 PM", icon: "process" },
      { label: "Shipped", desc: "Handed over to Delhivery. AWB: DEL7731094882", date: "Mar 16, 10:00 AM", icon: "truck" },
      { label: "Out for Delivery", desc: "Your package is with the delivery executive.", date: null, icon: "warehouse" },
      { label: "Delivered", desc: "Package delivered successfully.", date: null, icon: "box" },
    ],
  },
};
